
ALTER TABLE "Subscription" ADD COLUMN     "customModuleFee" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "customerName" TEXT,
ADD COLUMN     "licenseCost" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ALTER COLUMN "userCount" SET DEFAULT 10;
