

ALTER TABLE "Subscription" ADD COLUMN     "permissions" TEXT[],
ADD COLUMN     "role" TEXT NOT NULL DEFAULT 'TENANT_ADMIN',
ADD COLUMN     "setupFee" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "trainingFee" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ALTER COLUMN "userCount" SET NOT NULL,
ALTER COLUMN "userCount" SET DEFAULT 1;


CREATE UNIQUE INDEX "Subscription_stripeSubId_key" ON "Subscription"("stripeSubId");
