

CREATE TYPE "EnterpriseRole" AS ENUM ('SUPER_ADMIN', 'TENANT_ADMIN', 'WMS_MANAGER', 'TMS_MANAGER', 'PROCUREMENT_OFFICER', 'FINANCE_CONTROLLER', 'SUPPLY_CHAIN_ANALYST', 'INVENTORY_CLERK', 'VENDOR_REPRESENTATIVE', 'COMPLIANCE_AUDITOR', 'ADMIN', 'MANAGER', 'STAFF', 'EDITOR');


ALTER TABLE "Role" DROP COLUMN "name",
ADD COLUMN     "name" "EnterpriseRole" NOT NULL;


CREATE UNIQUE INDEX "Role_name_tenantId_key" ON "Role"("name", "tenantId");
