syntax = "proto3";

package auth;

service AuthServiceGrpc {
  rpc RegisterTenant (RegisterTenantRequest) returns (AuthResponse);
  rpc Login (LoginRequest) returns (AuthResponse);
  rpc CreateTenantUser (CreateTenantUserRequest) returns (AuthResponse);
}

message RegisterTenantRequest {
  string companyName = 1;
  string slug = 2;
  string email = 3;
  string password = 4;
  string firstName = 5;
  string lastName = 6;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message CreateTenantUserRequest {
  string tenantId = 1;
  string firstName = 2;
  string lastName = 3;
  string email = 4;
  string password = 5;
  string roleId = 6;
}

message AuthResponse {
  bool success = 1;
  string message = 2;
  string accessToken = 3;
  string refreshToken = 4;
  string userJson = 5;
}